/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/bcv/realtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime Bcv
         * @description Retrieve live exchange rates matching structural parser elements for dominant assets (USD/EUR) directly from the BCV portal.
         */
        get: operations["realtime_bcv_api_v1_bcv_realtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bcv/dolar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dolar Bcv
         * @description Provide the daily historical dollar exchange rate synchronized inside the active ledger.
         */
        get: operations["dolar_bcv_api_v1_bcv_dolar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bcv/euro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Euro Bcv
         * @description Provide the daily historical euro exchange rate synchronized inside the active ledger.
         */
        get: operations["euro_bcv_api_v1_bcv_euro_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bcv/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Bcv
         * @description Query database state blocks matching any specific official asset rate recorded on the system.
         */
        get: operations["query_bcv_api_v1_bcv_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bcv/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations["get_all_api_v1_bcv_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dolar/dolar_promedio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dolar Promedio
         * @description Returns the USD and EUR values ​​at the BCV, the USDT value on Binance P2P at the time of the query, and the average price between USD_BCV and USDT.
         */
        get: operations["dolar_promedio_api_v1_dolar_dolar_promedio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dolar/realtime_dolar_promedio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime Dolar Promedio
         * @description Returns the USD and EUR values ​​at the BCV, the USDT value on Binance P2P at the time of the query, and the average price between USD_BCV and USDT.
         */
        get: operations["realtime_dolar_promedio_api_v1_dolar_realtime_dolar_promedio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binance/realtime_ves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Realtime Binance Ves
         * @description Returns the averge exchange rate in the P2P Binance market at the moment of the request.
         */
        get: operations["realtime_binance_ves_api_v1_binance_realtime_ves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binance/real_time_pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Request for a specific pair in Binance P2P market
         * @description Returns the P2P average exchange rate for the selected pair, and a list of the first 20 prices in the market.
         */
        get: operations["get_binance_pair_api_v1_binance_real_time_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binance/ves_usdt_pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ves Usdt Pair
         * @description Returns de VES/USDT pair in BUY and SELL trade type from the last register of the database.
         */
        get: operations["get_ves_usdt_pair_api_v1_binance_ves_usdt_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/binance/pairs_last_record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pairs Last Record
         * @description Returns the last record of a given pair
         */
        get: operations["get_pairs_last_record_api_v1_binance_pairs_last_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/bcv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical BCV rates by currency and date range
         * @description Return historical official BCV rates for a specific currency, with optional date range filter.
         */
        get: operations["history_bcv_api_v1_history_bcv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/binance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical Binance P2P rates by pair and date range
         * @description Return historical Binance P2P rates for a specific pair (fiat/asset), with optional date range filter.
         */
        get: operations["history_binance_api_v1_history_binance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/fiat-pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * [Experimental] Historical cross fiat pair rates (VES→PEN, etc.)
         * @description [Experimental] Return historical cross-exchange rates between two fiat currencies calculated from Binance P2P records.
         *
         *     **WARNING**: This endpoint uses the `get_historical_pair` method from `FiatExchangeService` which has not been thoroughly tested yet. Results may be inaccurate or require adjustments.
         */
        get: operations["history_fiat_pair_api_v1_history_fiat_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get fiat/fiat pair from last database record.
         * @description Returns the average exchange rate for the selected pair based on stored operational database blocks.
         *
         *     This route evaluates metrics used to estimate remittance conversions across both directions.
         */
        get: operations["get_fiat_pair_api_v1_arbitrage_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/real_time_pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get fiat/fiat pair fetching prices direct from Binance.
         * @description Returns the dynamic live pricing metrics for the selected fiat assets mapping order books directly.
         */
        get: operations["get_real_time_pair_api_v1_arbitrage_real_time_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/arbitrage/today_pen_ves_pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the actual arbitrage values for VES/PES pair on Binance.
         * @description Returns the VES/PEN pair for arbitrage operations.
         */
        get: operations["get_today_pen_ves_pair_api_v1_arbitrage_today_pen_ves_pair_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck endpoint */
        get: operations["healthcheck_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArbitrageResponse
         * @description Esquema de respuesta de los cálculos de arbitraje entre dos monedas fiat con base a una tercera moneda (e.g.: USDT).
         *
         *     Attributes:
         *         ven_to_peru_adquisition_rate (float): Tasa de adquisición del negocio para enviar de Venezuela a Perú.
         *         peru_to_ven_adquisition_rate (float): Tasa de adquisición del negocio para enviar de Perú a Venezuela.
         *         ven_to_peru_customer_price (float): Precio de las remesas para el cliente de Venezuela a Perú.
         *         peru_to_ven_customer_price (float): Precio de las remesas para el cliente de Perú a Venezuela.
         * @example {
         *       "peru_to_ven_adquisition_rate": 0.08,
         *       "peru_to_ven_customer_price": 0.09,
         *       "ven_to_peru_adquisition_rate": 231.2,
         *       "ven_to_peru_customer_price": 250
         *     }
         */
        ArbitrageResponse: {
            /** Ven To Peru Adquisition Rate */
            ven_to_peru_adquisition_rate: number;
            /** Peru To Ven Adquisition Rate */
            peru_to_ven_adquisition_rate: number;
            /** Ven To Peru Customer Price */
            ven_to_peru_customer_price: number;
            /** Peru To Ven Customer Price */
            peru_to_ven_customer_price: number;
        };
        /**
         * BCVCurrencyListResponse
         * @description Schema for list response
         *
         *     Attributes:
         *         currencies (List[BCVCurrencyResponse]): List of BCVCurrencyResponse objects
         *         count (int): total amount of BCVCurrencyResponse objects.
         */
        BCVCurrencyListResponse: {
            /**
             * Currencies
             * @default []
             */
            currencies: components["schemas"]["BCVCurrencyResponse"][];
            /**
             * Count
             * @default 0
             */
            count: number;
        };
        /**
         * BCVCurrencyRealTimeResponse
         * @description Schema for the real time response from BCV for a single currency.
         *
         *     Attributes:
         *         currency (Currency): Currency tracked by BCV.
         *         trade_type (TradeType): Trade type operation for the currency.
         *         rate (Optional[float]): Rate of the currency.
         *         date (datetime): Date of the response.
         * @example {
         *       "currency": "DOLAR",
         *       "date": "2025-11-21T07:43:14.890702",
         *       "rate": 245.545621
         *     }
         */
        BCVCurrencyRealTimeResponse: {
            currency: components["schemas"]["Currency"];
            /** @default SELL */
            trade_type: components["schemas"]["TradeType"];
            /** Rate */
            rate: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /**
         * BCVCurrencyResponse
         * @description Schema for the response from BCV for a single currency.
         *
         *     Attributes:
         *         id (UUID): Unique identifier for the record.
         *         currency (Currency): Currency tracked by BCV.
         *         trade_type (TradeType): Trade type operation for the currency.
         *         rate (Optional[float]): Rate of the currency.
         *         date (datetime): Date of the response.
         * @example {
         *       "currency": "DOLAR",
         *       "date": "2025-11-21T07:43:14.890702",
         *       "id": "123e4567-e89b-12d3-a456-426614174000",
         *       "rate": 245.545621,
         *       "trade_type": "SELL"
         *     }
         */
        BCVCurrencyResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            currency: components["schemas"]["Currency"];
            /** @default SELL */
            trade_type: components["schemas"]["TradeType"];
            /** Rate */
            rate: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /**
         * BCVResponse
         * @description Schema for the general response from BCV to all currencies.
         *
         *     Attributes:
         *         dolar (Optional[BCVCurrencyResponse]): BCV dolar response.
         *         euro (Optional[BCVCurrencyResponse]): BCV euro response.
         *         yuan (Optional[BCVCurrencyResponse]): BCV yuan response.
         *         lira (Optional[BCVCurrencyResponse]): BCV lira response.
         *         rublo (Optional[BCVCurrencyResponse]): BCV rublo response.
         * @example {
         *       "dolar": {
         *         "currency": "DOLAR",
         *         "date": "2025-11-21T07:43:14.890702",
         *         "rate": 245.545621
         *       },
         *       "euro": {
         *         "currency": "EUR",
         *         "date": "2025-11-21T07:43:14.890702",
         *         "rate": 260.123456
         *       },
         *       "lira": {
         *         "currency": "TRY",
         *         "date": "2025-11-21T07:43:14.890702",
         *         "rate": 12.345678
         *       },
         *       "rublo": {
         *         "currency": "RUB",
         *         "date": "2025-11-21T07:43:14.890702",
         *         "rate": 3.456789
         *       },
         *       "yuan": {
         *         "currency": "CNY",
         *         "date": "2025-11-21T07:43:14.890702",
         *         "rate": 34.56789
         *       }
         *     }
         */
        BCVResponse: {
            dolar: components["schemas"]["BCVCurrencyResponse"] | null;
            euro: components["schemas"]["BCVCurrencyResponse"] | null;
            yuan: components["schemas"]["BCVCurrencyResponse"] | null;
            lira: components["schemas"]["BCVCurrencyResponse"] | null;
            rublo: components["schemas"]["BCVCurrencyResponse"] | null;
        };
        /**
         * BinanceAsset
         * @description Enum for crypto assets in Binance P2P. Only stablecoins are supported.
         *
         *     Attributes:
         *         USDT (str): Tether.
         *         USDC (str): USD Coin.
         *         DAI (str): Dai.
         * @enum {string}
         */
        BinanceAsset: "USDT" | "USDC" | "DAI";
        /**
         * BinanceCurrencyListResponse
         * @description Paginated collection payload structure aggregating multiple rate response items.
         *
         *     This layout ensures clients receive consistency concerning pagination states, binding both the requested records window slice and the real overall table records total.
         *
         *     Attributes:
         *         currencies (List[BinanceCurrencyResponse]): Collection list containing validated rate objects.
         *         count (int): Absolute global count matching filters to manage client pagination.
         */
        BinanceCurrencyListResponse: {
            /**
             * Currencies
             * @description Collection list containing validated rate dataset representations.
             */
            currencies: components["schemas"]["BinanceCurrencyResponse"][];
            /**
             * Count
             * @description Absolute global count matching filters used to manage client pagination states.
             */
            count: number;
        };
        /**
         * BinanceCurrencyResponse
         * @description Serialization model representing data layout output parsed to the clients.
         *
         *     This schema includes database-generated tracking fields like 'id' and 'date' and structures the individual exchange rate records returned by the endpoints.
         *
         *     Attributes:
         *         id (UUID): Unique database auto-generated record token identifier.
         *         fiat (FiatCurrency): The fiat currency target recorded for the trading pair.
         *         asset (BinanceAsset): The digital asset stablecoin cryptocurrency recorded.
         *         trade_type (TradeType): The P2P book perspective recorded (BUY or SELL).
         *         average_price (float): The persistent calculated historical average price.
         *         median_price (float): The persistent calculated historical median price.
         *         date (datetime): The UTC timestamp when the metrics were written to the database.
         */
        BinanceCurrencyResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique database auto-generated record token identifier.
             */
            id: string;
            /** @description The fiat currency of the trading pair used in the P2P market query. */
            fiat: components["schemas"]["FiatCurrency"];
            /** @description The digital asset or stablecoin cryptocurrency being quoted. */
            asset: components["schemas"]["BinanceAsset"];
            /** @description The P2P operation perspective, representing either BUY or SELL order books. */
            trade_type: components["schemas"]["TradeType"];
            /**
             * Average Price
             * @description The calculated average price of the top active orders at execution time.
             */
            average_price: number | null;
            /**
             * Median Price
             * @description The calculated median price of the top active orders at execution time.
             */
            median_price: number | null;
            /**
             * Date
             * Format: date-time
             * @description The UTC timestamp when the query metrics were written to the database.
             */
            date: string;
        };
        /**
         * BinanceRealTimeResponse
         * @description Schema for the response from Binance P2P.
         *
         *     Attributes:
         *         fiat (FiatCurrency): Fiat currency (e.g., VES, PEN).
         *         asset (BinanceAsset): Asset (USDT, BTC, etc).
         *         trade_type (TradeType): Trade type (BUY or SELL).
         *         prices (Optional[List[float]]): List of prices. Can be empty or None if Binance returns no data.
         *         average_price (Optional[float]): Average price. Null if no data.
         *         median_price (Optional[float]): Median price. Null if no data.
         * @example {
         *       "asset": "USDT",
         *       "average_price": 347.16,
         *       "fiat": "VES",
         *       "median_price": 347,
         *       "prices": [
         *         345.5,
         *         346.2,
         *         347,
         *         348.1,
         *         349
         *       ],
         *       "trade_type": "BUY"
         *     }
         * @example {
         *       "asset": "USDT",
         *       "fiat": "VES",
         *       "prices": [],
         *       "trade_type": "BUY"
         *     }
         */
        BinanceRealTimeResponse: {
            fiat: components["schemas"]["FiatCurrency"];
            asset: components["schemas"]["BinanceAsset"];
            trade_type: components["schemas"]["TradeType"];
            /** Prices */
            prices?: number[] | null;
            /** Average Price */
            average_price?: number | null;
            /** Median Price */
            median_price?: number | null;
        };
        /**
         * Currency
         * @description Enum for representing currencies.
         *
         *     Attributes:
         *         DOLAR (str): Represents the US Dollar.
         *         EURO (str): Represents the Euro.
         *         YUAN (str): Represents the Yuan.
         *         LIRA (str): Represents the Turkish Lira.
         *         RUBLE (str): Represents the Russian Ruble.
         * @enum {string}
         */
        Currency: "dolar" | "euro" | "yuan" | "lira" | "rublo";
        /**
         * DolarResponse
         * @description Schema for dolar prices from BCV and Binance for Venezuela interest case.
         *
         *     Attributes:
         *         bcv_dolar (Optional[BCVCurrencyResponse]): BCV dolar response.
         *         bcv_euro (Optional[BCVCurrencyResponse]): BCV euro response.
         *         binance_usdt_ves_buy (Optional[BinanceCurrencyResponse]): Binance USDT/VES response at Buy trade type.
         *         average_usdt_ves (Optional[float]): Average price between BCV and Binance.
         *         date (datetime): Date of the response.
         * @example {
         *       "average_usdt_ves": 296.25,
         *       "bcv_dolar": {
         *         "currency": "USD",
         *         "date": "2025-11-21T00:00:00",
         *         "id": "sdf-1234-5678-9012",
         *         "rate": 245.54
         *       },
         *       "bcv_euro": {
         *         "currency": "EUR",
         *         "date": "2025-11-21T00:00:00",
         *         "id": "sdf-1234-5678-9012",
         *         "rate": 260.12
         *       },
         *       "binance_usdt_ves_buy": {
         *         "asset": "USDT",
         *         "average_price": 346.97,
         *         "date": "2025-11-21T09:00:00",
         *         "fiat": "VES",
         *         "id": "sdf-1234-5678-9012",
         *         "trade_type": "BUY"
         *       },
         *       "date": "2025-11-21T09:00:00"
         *     }
         */
        DolarResponse: {
            bcv_dolar: components["schemas"]["BCVCurrencyResponse"] | null;
            bcv_euro: components["schemas"]["BCVCurrencyResponse"] | null;
            binance_usdt_ves_buy: components["schemas"]["BinanceCurrencyResponse"] | null;
            /** Average Usdt Ves */
            average_usdt_ves: number | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /**
         * FiatCurrency
         * @description Enum for fiat currencies in Binance P2P.
         *
         *     Attributes:
         *         VES (str): Venezuelan Bolívar.
         *         PEN (str): Peruvian Sol.
         *         USD (str): United States Dollar.
         *         USDT (str): Tether.
         *         EUR (str): Euro.
         * @enum {string}
         */
        FiatCurrency: "VES" | "PEN" | "USD" | "USDT" | "EUR";
        /**
         * FiatPairResponse
         * @description Schema for fiat pair prices from Binance.
         *
         *     Attributes:
         *         fiat_1_p2p_buy (Union[BinanceCurrencyResponse, BinanceRealTimeResponse]): Fiat 1 P2P response for buy.
         *         fiat_1_p2p_sell (Union[BinanceCurrencyResponse, BinanceRealTimeResponse]): Fiat 1 P2P response for sell.
         *         fiat_2_p2p_buy (Union[BinanceCurrencyResponse, BinanceRealTimeResponse]): Fiat 2 P2P response for buy.
         *         fiat_2_p2p_sell (Union[BinanceCurrencyResponse, BinanceRealTimeResponse]): Fiat 2 P2P response for sell.
         *         average_exchange_rate_f1_f2 (Optional[float]): Exchange rate from Fiat 1 to Fiat 2.
         *         average_exchange_rate_f2_f1 (Optional[float]): Exchange rate from Fiat 2 to Fiat 1.
         *         date (datetime): Date of the response.
         * @example {
         *       "average_exchange_rate_f1_f2": 0.0108,
         *       "average_exchange_rate_f2_f1": 92.266,
         *       "date": "2025-11-21T09:00:00",
         *       "fiat_1_p2p_buy": {
         *         "asset": "USDT",
         *         "average_price": 346.23,
         *         "fiat": "VES",
         *         "median_price": 346.2,
         *         "prices": [
         *           345.5,
         *           346.2,
         *           347
         *         ],
         *         "trade_type": "BUY"
         *       },
         *       "fiat_1_p2p_sell": {
         *         "asset": "USDT",
         *         "average_price": 344.5,
         *         "fiat": "VES",
         *         "median_price": 344.5,
         *         "prices": [
         *           344,
         *           344.5,
         *           345
         *         ],
         *         "trade_type": "SELL"
         *       },
         *       "fiat_2_p2p_buy": {
         *         "asset": "USDT",
         *         "average_price": 3.76,
         *         "fiat": "PEN",
         *         "median_price": 3.76,
         *         "prices": [
         *           3.75,
         *           3.76,
         *           3.77
         *         ],
         *         "trade_type": "BUY"
         *       },
         *       "fiat_2_p2p_sell": {
         *         "asset": "USDT",
         *         "average_price": 3.75,
         *         "fiat": "PEN",
         *         "median_price": 3.75,
         *         "prices": [
         *           3.74,
         *           3.75,
         *           3.76
         *         ],
         *         "trade_type": "SELL"
         *       }
         *     }
         * @example {
         *       "date": "2025-11-21T09:00:00",
         *       "fiat_1_p2p_buy": {
         *         "asset": "USDT",
         *         "fiat": "VES",
         *         "prices": [],
         *         "trade_type": "BUY"
         *       },
         *       "fiat_1_p2p_sell": {
         *         "asset": "USDT",
         *         "fiat": "VES",
         *         "prices": [],
         *         "trade_type": "SELL"
         *       },
         *       "fiat_2_p2p_buy": {
         *         "asset": "USDT",
         *         "average_price": 3.76,
         *         "fiat": "PEN",
         *         "median_price": 3.76,
         *         "prices": [
         *           3.75,
         *           3.76,
         *           3.77
         *         ],
         *         "trade_type": "BUY"
         *       },
         *       "fiat_2_p2p_sell": {
         *         "asset": "USDT",
         *         "average_price": 3.75,
         *         "fiat": "PEN",
         *         "median_price": 3.75,
         *         "prices": [
         *           3.74,
         *           3.75,
         *           3.76
         *         ],
         *         "trade_type": "SELL"
         *       }
         *     }
         */
        FiatPairResponse: {
            /** Fiat 1 P2P Buy */
            fiat_1_p2p_buy: components["schemas"]["BinanceCurrencyResponse"] | components["schemas"]["BinanceRealTimeResponse"];
            /** Fiat 1 P2P Sell */
            fiat_1_p2p_sell: components["schemas"]["BinanceCurrencyResponse"] | components["schemas"]["BinanceRealTimeResponse"];
            /** Fiat 2 P2P Buy */
            fiat_2_p2p_buy: components["schemas"]["BinanceCurrencyResponse"] | components["schemas"]["BinanceRealTimeResponse"];
            /** Fiat 2 P2P Sell */
            fiat_2_p2p_sell: components["schemas"]["BinanceCurrencyResponse"] | components["schemas"]["BinanceRealTimeResponse"];
            /** Average Exchange Rate F1 F2 */
            average_exchange_rate_f1_f2: number | null;
            /** Average Exchange Rate F2 F1 */
            average_exchange_rate_f2_f1: number | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RealTimeDolarResponse
         * @description Schema for dolar prices from BCV and Binance for Venezuela interest case.
         *
         *     Attributes:
         *         bcv_dolar (Optional[BCVCurrencyRealTimeResponse]): BCV dolar response.
         *         bcv_euro (Optional[BCVCurrencyRealTimeResponse]): BCV euro response.
         *         binance_usdt_ves_buy (Optional[BinanceRealTimeResponse]): Binance USDT/VES response at Buy trade type.
         *         average_usdt_ves (Optional[float]): Average price between BCV and Binance.
         *         date (datetime): Date of the response.
         * @example {
         *       "average_usdt_ves": 296.25,
         *       "bcv_dolar": {
         *         "currency": "USD",
         *         "date": "2025-11-21T00:00:00",
         *         "rate": 245.54
         *       },
         *       "bcv_euro": {
         *         "currency": "EUR",
         *         "date": "2025-11-21T00:00:00",
         *         "rate": 260.12
         *       },
         *       "binance_usdt_ves_buy": {
         *         "asset": "USDT",
         *         "average_price": 346.97,
         *         "date": "2025-11-21T09:00:00",
         *         "fiat": "VES",
         *         "trade_type": "BUY"
         *       },
         *       "date": "2025-11-21T09:00:00"
         *     }
         */
        RealTimeDolarResponse: {
            bcv_dolar: components["schemas"]["BCVCurrencyRealTimeResponse"] | null;
            bcv_euro: components["schemas"]["BCVCurrencyRealTimeResponse"] | null;
            binance_usdt_ves_buy: components["schemas"]["BinanceRealTimeResponse"] | null;
            /** Average Usdt Ves */
            average_usdt_ves: number | null;
            /**
             * Date
             * Format: date-time
             */
            date: string;
        };
        /**
         * TradeType
         * @description Enum for trade types in Binance P2P platform.
         *
         *     Attributes:
         *         BUY (str): Buy trade type.
         *         SELL (str): Sell trade type.
         * @enum {string}
         */
        TradeType: "BUY" | "SELL";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    realtime_bcv_api_v1_bcv_realtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVCurrencyRealTimeResponse"][];
                };
            };
        };
    };
    dolar_bcv_api_v1_bcv_dolar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVCurrencyResponse"] | null;
                };
            };
        };
    };
    euro_bcv_api_v1_bcv_euro_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVCurrencyResponse"] | null;
                };
            };
        };
    };
    query_bcv_api_v1_bcv_query_get: {
        parameters: {
            query: {
                /** @description Target currency asset supported by the tracking matrix. */
                currency: components["schemas"]["Currency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVCurrencyResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_api_v1_bcv_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVResponse"] | null;
                };
            };
        };
    };
    dolar_promedio_api_v1_dolar_dolar_promedio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DolarResponse"] | null;
                };
            };
        };
    };
    realtime_dolar_promedio_api_v1_dolar_realtime_dolar_promedio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealTimeDolarResponse"];
                };
            };
        };
    };
    realtime_binance_ves_api_v1_binance_realtime_ves_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceRealTimeResponse"] | null;
                };
            };
        };
    };
    get_binance_pair_api_v1_binance_real_time_pair_get: {
        parameters: {
            query: {
                /** @description Target local fiat currency (e.g., VES, PEN). */
                fiat: components["schemas"]["FiatCurrency"];
                /** @description Crypto token backing transaction pairs. */
                asset?: components["schemas"]["BinanceAsset"];
                /** @description Order book tracking target perspective. */
                trade_type?: components["schemas"]["TradeType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceRealTimeResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ves_usdt_pair_api_v1_binance_ves_usdt_pair_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceCurrencyResponse"][] | null;
                };
            };
        };
    };
    get_pairs_last_record_api_v1_binance_pairs_last_record_get: {
        parameters: {
            query: {
                /** @description Target historical operational fiat asset. */
                fiat: components["schemas"]["FiatCurrency"];
                /** @description Crypto token matching data arrays. */
                asset?: components["schemas"]["BinanceAsset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceCurrencyResponse"][] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_bcv_api_v1_history_bcv_get: {
        parameters: {
            query?: {
                /** @description Currency to consult (DOLAR, EURO, YUAN, LIRA, RUBLE). */
                currency?: components["schemas"]["Currency"];
                /** @description Trade type (BUY, SELL). */
                trade_type?: components["schemas"]["TradeType"];
                /** @description Start date (YYYY-MM-DDTHH:MM:SS). */
                start_date?: string | null;
                /** @description End date (YYYY-MM-DDTHH:MM:SS). */
                end_date?: string | null;
                /** @description Records to skip (pagination). */
                skip?: number;
                /** @description Maximum records to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BCVCurrencyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_binance_api_v1_history_binance_get: {
        parameters: {
            query?: {
                /** @description Fiat currency (VES, PEN, COP, etc.). */
                fiat?: components["schemas"]["FiatCurrency"];
                /** @description Crypto asset (USDT, BTC, etc.). */
                asset?: components["schemas"]["BinanceAsset"];
                /** @description Trade type (BUY, SELL). */
                trade_type?: components["schemas"]["TradeType"];
                /** @description Start date (YYYY-MM-DDTHH:MM:SS). */
                start_date?: string | null;
                /** @description End date (YYYY-MM-DDTHH:MM:SS). */
                end_date?: string | null;
                /** @description Records to skip (pagination). */
                skip?: number;
                /** @description Maximum records to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BinanceCurrencyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_fiat_pair_api_v1_history_fiat_pair_get: {
        parameters: {
            query: {
                /** @description Source fiat currency. */
                fiat_1: components["schemas"]["FiatCurrency"];
                /** @description Destination fiat currency. */
                fiat_2: components["schemas"]["FiatCurrency"];
                /** @description Start date (YYYY-MM-DDTHH:MM:SS). */
                start_date: string;
                /** @description End date (YYYY-MM-DDTHH:MM:SS). */
                end_date: string;
                /** @description Records to skip (pagination). */
                skip?: number;
                /** @description Maximum records to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatPairResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fiat_pair_api_v1_arbitrage_pair_get: {
        parameters: {
            query: {
                /** @description First local fiat currency tracking asset. */
                fiat_1: components["schemas"]["FiatCurrency"];
                /** @description Second local fiat currency tracking asset. */
                fiat_2: components["schemas"]["FiatCurrency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatPairResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_real_time_pair_api_v1_arbitrage_real_time_pair_get: {
        parameters: {
            query: {
                /** @description First local fiat currency tracking asset. */
                fiat_1: components["schemas"]["FiatCurrency"];
                /** @description Second local fiat currency tracking asset. */
                fiat_2: components["schemas"]["FiatCurrency"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FiatPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_pen_ves_pair_api_v1_arbitrage_today_pen_ves_pair_get: {
        parameters: {
            query?: {
                /** @description Reveneu rate for agency */
                reveneu_rate?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArbitrageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthcheck_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
